name: Publish package to the Maven Central Repository
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: import-gpg-key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASS_PHRASE }}
          trust_level: 5

      - name: list-gpg-secret-keys
        run: gpg --list-secret-keys --keyid-format=long

      - name: Configure Git user
        run: |
          git config user.email "oss@carbonbulls.com"
          git config user.name "GitHub Actions"

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DEPLOY_KNOWN_HOSTS }}

      - name: Publish package
        run: mvn --no-transfer-progress --batch-mode release:prepare release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
