name: Verify

# trigger on push to branches and PR
on:
  push:
    branch:
  pull_request:

jobs:
  build:
    name: 'with JDK ${{ matrix.jdk }}'
    strategy:
      fail-fast: false
      matrix:
        jdk: [ 11, 17 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.jdk }}'
          distribution: 'temurin'
          cache: maven

      - name: import-gpg-key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASS_PHRASE }}
          trust_level: 5

      - name: list-gpg-secret-keys
        run: gpg --list-secret-keys --keyid-format=long

      - name: Build and verify
        run: ./mvnw verify --batch-mode --no-transfer-progress --errors
